### ISSUE TITLE
2/14 after GDS meeting

### ISSUE THREAD

**Issue by tshaw11** [shawman777/gds#47]
1. moved to issue 63

 2. we need to add "questions? please contact..."

3. Registration page--may want to say "congratulations you have successfully registered"  

4. was moved to issue #62

5. Food preference--we may want to add a note that says "only those on the first shift will get food or something like that"

6. confirmation page--"Additional" is ms 

7. change "tools and equipment" to "can you bring any of the following to use

8. under "tools and equipment"  add "none"

**Comment by tshaw11** [comment]
#7 -can none be mutually exclusive?

**Comment by shawman777** [comment]
#5 What color would you like? Or do you want it bolded or italic?
#7 Will work on this

**Comment by tshaw11** [comment]
maybe bold not sure..just a way so it stands out


-----Original Message-----

**Comment by shawman777** [comment]
#7 None and No experience are both handled as follows:
If 'None' clicked then the other tools are cleared if checked and disabled. If 'None' is unchecked then the other tools are enabled again. (Same for 'No experience')

**Comment by tshaw11** [comment]
this is done bolded is good
none is disabling the others 
will close this out
