### ISSUE TITLE
Confirmation page

### ISSUE THREAD

**Issue by shawman777** [shawman777/gds#64]
Clean up the look and feel of the confirmation page

**Comment by tshaw11** [comment]
Under special skills if nothing appears can we change the confirmation text from "false" to "no"

**Comment by shawman777** [comment]
Moving this back to 'In Progress', so I can work on the recommendation

**Comment by tshaw11** [comment]
if you could add one more thing to the text  "if any of the information is missing or incorrect please email Volunteers@..."

**Comment by tshaw11** [comment]
done
