### ISSUE TITLE
days available to volunteer looks really strange

### ISSUE THREAD

**Issue by tshaw11** [shawman777/gds#67]
its staggered but it's hard to understand

**Comment by shawman777** [comment]
Can you add a screen shot or show me tonight? I am unclear here. The registration page looks ok to me

**Comment by tshaw11** [comment]
it's only when the screen is not maximized


-----Original Message-----

**Comment by shawman777** [comment]
Is this something we may be able to work on after the initial release?

**Comment by tshaw11** [comment]
Yes just add please maximize your screen 


Sent from my Sprint Samsung Galaxy S® 6.-------- Original message --------

**Comment by shawman777** [comment]
Yes, that is a good suggestion.

Thanks.

On Wed, Mar 9, 2016, 10:49 AM tshaw11 <notifications@github.com> wrote:

> Yes just add please maximize your screen
>
>
> Sent from my Sprint Samsung Galaxy S® 6.-------- Original message --------
> From: shawman777 <notifications@github.com>
> Date: 03/09/2016 10:45 AM (GMT-06:00)
> To: shawman777/gds <gds@noreply.github.com>
> Cc: tshaw11 <tasshaw@aol.com>
> Subject: Re: [gds] days available to volunteer looks really strange (#67)
>
> Is this something we may be able to work on after the initial release?
>
> —
> Reply to this email directly or view it on GitHub.
>
>
>
>
>
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shawman777/gds/issues/67#issuecomment-194392090>.
>
-- 
-    Eddie

**Comment by tshaw11** [comment]
this is a good solution for now
